/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package Jflextest;
import static Jflextest.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>NewLexer.flex</tt>
 */
class NewLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\41\1\42\1\42\1\41\22\0\1\3\5\0\1\33"+
    "\1\0\1\23\1\24\1\47\1\40\1\0\1\43\1\45\1\37\12\2"+
    "\1\0\1\31\1\36\1\34\1\35\6\0\1\46\25\0\1\27\1\0"+
    "\1\30\3\0\1\21\1\20\1\1\1\17\1\10\1\5\1\1\1\7"+
    "\1\4\1\1\1\22\1\12\1\1\1\11\1\14\2\1\1\15\1\13"+
    "\1\6\2\1\1\16\3\1\1\25\1\32\1\26\7\0\1\42\u05da\0"+
    "\12\44\206\0\12\44\306\0\12\44\u019c\0\12\44\166\0\12\44\166\0"+
    "\12\44\166\0\12\44\166\0\12\44\166\0\12\44\166\0\12\44\166\0"+
    "\12\44\166\0\12\44\340\0\12\44\166\0\12\44\106\0\12\44\u0116\0"+
    "\12\44\106\0\12\44\u0746\0\12\44\46\0\12\44\u012c\0\12\44\200\0"+
    "\12\44\246\0\12\44\6\0\12\44\266\0\12\44\126\0\12\44\206\0"+
    "\12\44\6\0\12\44\u03ce\0\1\42\1\42\u85f6\0\12\44\u02a6\0\12\44"+
    "\46\0\12\44\306\0\12\44\166\0\12\44\u0196\0\12\44\u5316\0\12\44"+
    "\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\10\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\1\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\1\1\23\1\24"+
    "\2\0\2\22\1\25\3\2\1\0\1\2\1\26\1\2"+
    "\1\27\1\30\1\31\1\32\1\33\1\4\3\0\1\22"+
    "\2\34\1\0\1\22\2\34\1\35\4\2\1\36\1\37"+
    "\1\40\2\2\1\41\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\50\0\50\0\50"+
    "\0\50\0\50\0\50\0\50\0\u0208\0\u0230\0\u0258\0\u0280"+
    "\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370\0\50\0\u0398"+
    "\0\u03c0\0\u03e8\0\u0410\0\u0438\0\120\0\u0460\0\u0488\0\u04b0"+
    "\0\u04d8\0\u0500\0\120\0\u0528\0\50\0\50\0\50\0\50"+
    "\0\50\0\50\0\u0550\0\u0370\0\u0578\0\u05a0\0\u03c0\0\u05c8"+
    "\0\u05f0\0\u05f0\0\u0410\0\u0438\0\120\0\u0618\0\u0640\0\u0668"+
    "\0\u0690\0\50\0\120\0\120\0\u06b8\0\u06e0\0\120\0\120";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\3"+
    "\1\11\2\3\1\12\2\3\1\13\1\14\1\15\2\3"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\5\1\0"+
    "\1\34\1\35\1\36\1\2\1\37\51\0\1\3\1\40"+
    "\1\0\17\3\25\0\2\41\1\4\5\41\1\42\30\41"+
    "\2\0\1\41\1\43\1\44\1\42\1\41\3\0\1\5"+
    "\35\0\1\5\7\0\1\3\1\40\1\0\1\3\1\45"+
    "\15\3\26\0\1\3\1\40\1\0\10\3\1\46\6\3"+
    "\26\0\1\3\1\40\1\0\3\3\1\47\13\3\26\0"+
    "\1\3\1\40\1\0\6\3\1\50\10\3\26\0\1\3"+
    "\1\40\1\0\7\3\1\12\7\3\15\0\1\51\10\0"+
    "\1\3\1\40\1\0\3\3\1\52\13\3\26\0\1\3"+
    "\1\40\1\0\10\3\1\53\6\3\26\0\1\3\1\40"+
    "\1\0\11\3\1\54\5\3\57\0\1\55\50\0\1\56"+
    "\50\0\1\57\47\0\1\60\47\0\1\61\52\0\1\62"+
    "\12\0\1\35\35\0\1\63\3\0\1\35\1\64\4\0"+
    "\1\35\41\0\1\35\1\64\4\0\1\35\5\0\1\65"+
    "\33\0\1\35\1\66\1\65\3\0\1\66\41\0\1\66"+
    "\4\0\2\40\1\0\17\40\27\0\1\67\47\0\1\70"+
    "\35\0\1\71\2\0\1\71\1\72\5\0\1\73\5\0"+
    "\1\65\33\0\1\35\1\66\1\65\3\0\1\74\5\0"+
    "\1\65\33\0\1\66\1\0\1\65\2\0\1\3\1\40"+
    "\1\0\11\3\1\75\5\3\26\0\1\3\1\40\1\0"+
    "\4\3\1\76\12\3\26\0\1\3\1\40\1\0\7\3"+
    "\1\77\7\3\65\0\1\63\10\0\1\3\1\40\1\0"+
    "\1\100\16\3\26\0\1\3\1\40\1\0\4\3\1\101"+
    "\12\3\40\0\1\102\36\0\1\72\35\0\1\71\2\0"+
    "\1\71\1\72\5\0\1\66\5\0\1\65\33\0\1\66"+
    "\1\0\1\65\3\0\1\70\41\0\1\72\5\0\1\72"+
    "\41\0\1\72\4\0\1\3\1\40\1\0\5\3\1\103"+
    "\11\3\26\0\1\3\1\40\1\0\4\3\1\104\12\3"+
    "\26\0\1\3\1\40\1\0\6\3\1\105\10\3\26\0"+
    "\1\3\1\40\1\0\15\3\1\106\1\3\26\0\1\3"+
    "\1\40\1\0\4\3\1\107\12\3\26\0\1\3\1\40"+
    "\1\0\16\3\1\110\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\13\1\7\11\12\1\1\11\1\1\2\0"+
    "\6\1\1\0\3\1\6\11\3\0\3\1\1\0\10\1"+
    "\1\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  NewLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  NewLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 262) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return ERROR;
          }
        case 35: break;
        case 2: 
          { lexeme =yytext(); return variable;
          }
        case 36: break;
        case 3: 
          { lexeme=yytext(); return numero;
          }
        case 37: break;
        case 4: 
          { /*Ignore*/
          }
        case 38: break;
        case 5: 
          { return OPENPARENTHESIS;
          }
        case 39: break;
        case 6: 
          { return CLOSEPARENTHESIS;
          }
        case 40: break;
        case 7: 
          { return OPENKEY;
          }
        case 41: break;
        case 8: 
          { return CLOSEKEY;
          }
        case 42: break;
        case 9: 
          { return OPENBRACKET;
          }
        case 43: break;
        case 10: 
          { return CLOSEBRACKET;
          }
        case 44: break;
        case 11: 
          { return SEMICOLON;
          }
        case 45: break;
        case 12: 
          { return igual;
          }
        case 46: break;
        case 13: 
          { return GREATER;
          }
        case 47: break;
        case 14: 
          { return LOWER;
          }
        case 48: break;
        case 15: 
          { return division;
          }
        case 49: break;
        case 16: 
          { return suma;
          }
        case 50: break;
        case 17: 
          { return resta;
          }
        case 51: break;
        case 18: 
          { lexeme=yytext(); return exponente;
          }
        case 52: break;
        case 19: 
          { return multiplicacion;
          }
        case 53: break;
        case 20: 
          { lexeme=yytext(); return ID;
          }
        case 54: break;
        case 21: 
          { return IF;
          }
        case 55: break;
        case 22: 
          { return DO;
          }
        case 56: break;
        case 23: 
          { return OR;
          }
        case 57: break;
        case 24: 
          { return AND;
          }
        case 58: break;
        case 25: 
          { return EQUALS;
          }
        case 59: break;
        case 26: 
          { return GREATER_EQUALS;
          }
        case 60: break;
        case 27: 
          { return LOWER_EQUALS;
          }
        case 61: break;
        case 28: 
          { lexeme=yytext(); return decimal;
          }
        case 62: break;
        case 29: 
          { return FOR;
          }
        case 63: break;
        case 30: 
          { lexeme=yytext(); return incremento;
          }
        case 64: break;
        case 31: 
          { return THEN;
          }
        case 65: break;
        case 32: 
          { return ELSE;
          }
        case 66: break;
        case 33: 
          { return WHILE;
          }
        case 67: break;
        case 34: 
          { return BREAK;
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
